### ISSUE TITLE
Error running the weather.py example

### ISSUE THREAD

**Issue by jonwolf-ibisa** [pjkundert/cpppo#11]
Hi, I'm new to **python** and I need to write a program using this **cpppo library** that needs to connect to a server running an Ethernet/IP simulator by Molex in an specific IP address on port 44818.

Using an Ethernet/IP object reader I need to validate that I'm connected and I need to show data from the controller, in this case (RSLinx Server), a first step will be to read object 0x01 that corresponds to the identity. (there's an image attached in this post that shows the Molex Ethernet/IP Simulator)

i wanted to test this weather.py example but I'm getting an error in the line _**from cpppo.server.enip import device, REAL**_ that tells me this:
_**The debugged program raised the exception unhandled ImportError
"No module named 'cpppo'"**_

I've already installed the cpppo library using the terminal command _pip install cpppo_, so, i've got the library installed already.

Could you guys please help with this matter.

Thanks so much in advance.

![ethernet_ip server molex](https://cloud.githubusercontent.com/assets/17366073/13199745/e6d1fcea-d7ff-11e5-8718-e0779159be60.png)

**Comment by pjkundert** [comment]
If you have installed 'cpppo' using 'pip install cpppo', but then your Python cannot find it -- make sure you are using the same Python.  This indicates that there is some issue with your Python installation, not with cpppo.

You might try 'python -m pip install cpppo'.  This will ensure that (at least) the same version of Python is being used to perform the pip install.

If, after a 'pip install whatever', you run python, get a '>>> ' prompt, and try 'import whatever'.  If this doesn't succeed, then the module you just installed didn't get installed correctly.  I'd recommend following some Python getting started documentation to get your feet wet, and work out all of the basic issues with working with Python, and then have another go...

Don't give up.  Working with Python on Windows is especially difficult vs. Mac or Linux.  But, once you've got all the Windows-y issues worked out, it seems to work OK.  Getting the "command line" to work right is especially problematic, but there are work-arounds in the https://github.com/pjkundert/cpppo.git documentation README.org.

Hope that helps.

**Comment by jonwolf-ibisa** [comment]
Hi pjkundert, thanks for the quick reply, I've **pip uninstall cpppo** and then **python -m pip install cpppo**  but I'm getting the same error, forgot to mention that I'm working on Virtual Box and Debian 8.3.0. on Windows 7.

![virtualbox_debian 8 3 0_20_02_2016_19_41_16](https://cloud.githubusercontent.com/assets/17366073/13200003/04695aa0-d80a-11e5-8243-4c92f0b47ef4.png)

**Comment by datasim** [comment]
I would recommend using the command-line.  It's probably an issue with your
IDE, not using the same version of Python as on your Debian installation,
or something.

I'd recommend installing other (simpler) modules, and testing them out,
'til you get it to work.  Then resume working with cpppo.  Follow the
getting started documentation for your IDE, perhaps?

--
    -pjk

**Comment by jonwolf-ibisa** [comment]
you were right datasim, running the program in terminal runs well, the problem is in Eric IDE, i need to configure some sort of path. Thanks
