### ISSUE TITLE
List available tags on PLC

### ISSUE THREAD

**Issue by rexnfx** [pjkundert/cpppo#25]
Is there any way to query a compactlogix using cpppo to determine which tags are available to read from?

**Comment by pjkundert** [comment]
There is a way -- but it isn't documented anywhere that I have been able to find.  I haven't had the time to research it, and no clients have been willing to fund this, so I'd be more than happy for someone to capture these CIP requests and implement this!

**Comment by rexnfx** [comment]
I have wireshark and a compactlogix plc, can you describe what i would need to connect to the compactlogix to capture this?
