### ISSUE TITLE
Issue of Installing from source

### ISSUE THREAD

**Issue by lgy194** [pjkundert/cpppo#41]
when I try to do as README file. 
there is a step on Page3: git clone git@github.com:pjkundert/cpppo.git
but system reply Permission denied(publickey).

I hope to know whether it is a problem for next steps. Thank you.

**Comment by pjkundert** [comment]
You need to have a Github account with SSH keys in order to use the SSH protocol (get@github.com:pjkundert/cpppo.git).  Use the HTTPS protocol instead: https://github.com/pjkundert/cpppo.git) to clone the repo.

**Comment by lgy194** [comment]
Thank you. I will try. Need I installed it on MiniCPS which on MiniNet? or Can install it on every Linux system
