### ISSUE TITLE
Cannot able to set the value SCADA[1]=99 in "enip_server -v --print SCADA[0-10]  SCADA[1]=99  'TEXT[1]=(SSTRING)"Hello, world!"' TEXT[0-3]"

### ISSUE THREAD

**Issue by arvindh123** [pjkundert/cpppo#52]
`PS D:\ppp\desktop\EIP> enip_server -v --print SCADA[0-10] SCADA[1]=99 'TEXT[1]=(SSTRING)"Hello, world!"' TEXT[0-3]
04-27 16:21:00.229 MainThread root     NORMAL   main       Loaded config files: []
04-27 16:21:00.229 MainThread enip.srv NORMAL   main       Delaying all responses by 0.0 seconds
04-27 16:21:00.230 MainThread enip.srv NORMAL   main       Creating tag: SCADA[0-10]                     INT[   1]
Traceback (most recent call last):
  File "c:\users\laptop81\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\laptop81\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Laptop81\AppData\Local\Programs\Python\Python36\Scripts\enip_server.exe\__main__.py", line 9, in <module>
  File "c:\users\laptop81\appdata\local\programs\python\python36\lib\site-packages\cpppo\server\enip\main.py", line 1134, in main
    assert tag_type in typenames, "Invalid tag type; must be one of %r ---your tage_type is - %r" % (list( typenames ),list(tag_type))
AssertionError: Invalid tag type; must be one of ['BOOL', 'INT', 'DINT', 'SINT', 'REAL', 'SSTRING', 'STRING'] ---your tage_type is - ['9', '9']`

I have  edited the code  @ "c:\users\laptop81\appdata\local\programs\python\python36\lib\site-packages\cpppo\server\enip\main.py", line 1134 to know the "tag_type"
        `assert tag_type in typenames, "Invalid tag type; must be one of %r ---your tage_type is - %r" % (list( typenames ),list(tag_type))`

Using Version Python 3.6

**Comment by pjkundert** [comment]
I would recommend trying the requests one at a time, and see if they work independently; if so, its a Windows command-line issue.  Attempt to quote the requests; quoting on the Windows command-line is very difficult...  See https://github.com/pjkundert/cpppo_positioner's README.
