### ISSUE TITLE
Question: Can this library be used to recieve generic CIP messages from a PLC?

### ISSUE THREAD

**Issue by abcasada** [pjkundert/cpppo#60]

**Comment by abcasada** [comment]
I've looked through the documentation and don't see any examples of this, but maybe I'm missing it due to not knowing a lot about the E/IP protocol.

**Comment by je13fr** [comment]
from command line, you can use:
python -m cpppo.server.enip.get_attribute '@0x93/3/10=(REAL)1.0'
Look in client secction for EIP Client, in previous doc it's server part who is documented
I hope it helps
